name: Warehouse check style
on:
  push:
    branches:
      - master
jobs:
  check-style-java:
    runs-on: [debian]
    steps:
      - name: Git clone project
        uses: actions/checkout@v2

      - name: Install project dependencies
        run: ./gradlew check -s
