name: Warehouse check style
on:
  push:
    branches:
      - master
jobs:
  check_style_java:
    runs-on: ubuntu_latest
    steps:
      - name: Git clone project
        uses: actions/checkout@v2

      - name: Set version java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install project dependencies
        run: ./gradlew check -s
